import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/session";

export async function POST(req: NextRequest) {
  try {
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { 
      productName, 
      price, 
      category, 
      title, 
      description,
      whatsappCaption,
      instagramCaption,
      reelScript,
      facebookAdText,
      hashtags,
      festivalBannerPrompt
    } = body;

    if (!productName || !price) {
      return NextResponse.json({ error: "Product name and price are required" }, { status: 400 });
    }

    const product = await prisma.product.create({
      data: {
        storeId: session.storeId,
        name: productName,
        price: parseFloat(price),
        category: category,
        whatsappCaption,
        instagramCaption,
        reelScript,
        facebookAdText,
        hashtags: JSON.stringify(hashtags || []),
        festivalBannerPrompt,
        // Save the AI optimized content as well
        description: description || "", // Using the rich description generated by AI
        isActive: true,
      },
    });

    return NextResponse.json({ success: true, productId: product.id });
  } catch (error) {
    console.error("[products/publish]", error);
    return NextResponse.json({ error: "Failed to publish product" }, { status: 500 });
  }
}
